version: 2

jobs:
    test:
        docker:
            - image: aaswenson/py3_sco2_reactor_tests
        steps:
            - checkout
            - run:
                 name: run tests
                 command: |
                     pytest
workflows:
    version: 2
    test:
        jobs:
            - test
